name: AirmatesApp
options:
  bundleIdPrefix: com.airmates
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.4"

settings:
  base:
    SWIFT_VERSION: "5.0"
    CLANG_CXX_LANGUAGE_STANDARD: "gnu++20"
    CLANG_ENABLE_MODULES: "YES"
    ENABLE_STRICT_OBJC_MSGSEND: "YES"
    GCC_WARN_64_TO_32_BIT_CONVERSION: "YES"
    GCC_WARN_ABOUT_RETURN_TYPE: "YES_ERROR"
    GCC_WARN_UNDECLARED_SELECTOR: "YES"
    GCC_WARN_UNINITIALIZED_AUTOS: "YES_AGGRESSIVE"
    GCC_WARN_UNUSED_FUNCTION: "YES"
    GCC_WARN_UNUSED_VARIABLE: "YES"
    MTL_FAST_MATH: "YES"
  configs:
    Debug:
      DEBUG_INFORMATION_FORMAT: "dwarf"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG $(inherited)"
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      GCC_DYNAMIC_NO_PIC: "NO"
      GCC_OPTIMIZATION_LEVEL: "0"
      ENABLE_TESTABILITY: "YES"
      ONLY_ACTIVE_ARCH: "YES"
      MTL_ENABLE_DEBUG_INFO: "INCLUDE_SOURCE"
      GCC_PREPROCESSOR_DEFINITIONS:
        - "DEBUG=1"
        - "$(inherited)"
    Release:
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
      SWIFT_COMPILATION_MODE: "wholemodule"
      ENABLE_NS_ASSERTIONS: "NO"
      VALIDATE_PRODUCT: "YES"
      MTL_ENABLE_DEBUG_INFO: "NO"
      COPY_PHASE_STRIP: "NO"

targets:
  AirmatesApp:
    type: application
    platform: iOS
    sources:
      - path: AirmatesApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.airmates.app
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: "1.0"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        GENERATE_INFOPLIST_FILE: "YES"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: "YES"
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: "YES"
        INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: "YES"
        TARGETED_DEVICE_FAMILY: "1,2"
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
